# Configurations
markdown: kramdown
kramdown:
    input: GFM
markdown_ext:  markdown,mkdown,mkdn,mkd,md
#highlighter: pygments
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data","prettify"]
# Permalinks
permalink:        /blog/:year/:month/:day/:title.html

# Setup
title:            'blog.mahlberg.io'
tagline:          'All the good things!'
description:      'Markus W Mahlberg''s blog'
url:              'https://blog.mahlberg.io'
baseurl:          'https://blog.mahlberg.io'
plugins: [jekyll-paginate]

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Markus W Mahlberg'

# Mailhide
mailhide:
 k: '012X9odBERvvGgowCQBH2jmQ=='
 c: 'KJMvzPEFJzWvpfyiR6rV4ICzkZbmvA0sHaovWr-ia3g='

#Social Media links (Use complete URL except for email)
dribbble:
email:          'markus@mahlberg.io'
facebook:       'https://www.facebook.com/mwmahlberg'
flickr:
github:         'https://github.com/mwmahlberg'
gplus:          'https://plus.google.com/u/0/+MarkusMahlberg/'
#instagram:
#pinterest:
#linkedin:       'https://ae.linkedin.com/in/olakara/'
linkedin:       'https://de.linkedin.com/in/mwmahlberg'
#rss:
stackoverflow:  'http://stackoverflow.com/users/1296707/markus-w-mahlberg'
twitter:        'https://twitter.com/mwmahlberg'

# Google Analytics
gahandler: 'UA-69721976-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'blogmahlbergio'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
